---
# tasks file for create_ec2_ova

- name: Launch EC2 Instance for OVA Export
  amazon.aws.ec2_instance:
    name: temp_instance
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ami_image_id }}"
    count: 1
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    security_group: "{{ ec2_security_group }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
    network_interfaces:
      - assign_public_ip: true
  register: ec2_ova_result

- name: Wait for instance to pass 2/2 checks using AWS CLI
  ansible.builtin.shell: |
    aws ec2 wait instance-status-ok \
    --instance-ids {{ ec2_ova_result.instances[0].instance_id }} \
    --region {{ aws_region }}
  changed_when: false

- name: Add new EC2 IP & ID to inventory group 'ova_instances'
  ansible.builtin.add_host:
    name: "{{ ec2_ova_result.instances[0].public_ip_address }}"
    groups: ova_instances
    ova_instance_public_ip: "{{ ec2_ova_result.instances[0].public_ip_address }}"

- name: Add 'ova_instance_id' variable to localhost
  ansible.builtin.add_host:
    name: localhost
    groups: all
    ova_instance_id: "{{ ec2_ova_result.instances[0].instance_id }}"
    ova_instance_public_ip: "{{ ec2_ova_result.instances[0].public_ip_address }}"
