---
# defaults file for create_ec2_vmdk
# these need to be made into surveys
aws_region: us-east-2

ec2_instance_type: t2.micro
ec2_image: ami-0a482bdfdf4a33e61
ec2_key_name: akalohi_aws_pem
ec2_security_group: my-security-group-1
ec2_subnet_id: subnet-0e7421b258ef5d274
ec2_instance_name: akalohi-vmdk-export