---
# tasks file for create_ec2_vhd

- name: Launch EC2 Dummy Instance for OVA Export
  amazon.aws.ec2_instance:
    name: dummy_instance
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ami_image_id }}"
    count: 1
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    security_group: "{{ ec2_security_group }}"
    state: running
    wait: true
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    session_token: "{{ aws_session_token }}"
    validate_certs: false
  register: ec2_dummy_result

- name: Wait for instance to pass 2/2 checks using AWS CLI
  ansible.builtin.command: >
    aws ec2 wait instance-status-ok
    --instance-ids {{ ec2_dummy_result.instances[0].instance_id }}
    --no-verify-ssl
    --region {{ aws_region }}
  changed_when: false

- name: Set 'dummy_ec2_instance_id' variable
  ansible.builtin.set_fact:
    dummy_ec2_instance_id: "{{ ec2_dummy_result.instances[0].instance_id }}"
