---
# tasks file for create_ec2_vhd

- name: Launch EC2 Dummy Instance for OVA Export
  amazon.aws.ec2_instance:
    name: dummy_instance
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ami_image_id }}"
    count: 1
    region: "{{ aws_region }}"
    state: running
    wait: true
  register: ec2_dummy_result

- name: Wait for instance to pass 2/2 checks using AWS CLI
  ansible.builtin.shell: |
    aws ec2 wait instance-status-ok \
    --instance-ids {{ ec2_dummy_result.instances[0].instance_id }} \
    --region {{ aws_region }}
  changed_when: false

- name: Set 'dummy_ec2_instance_id' variable
  ansible.builtin.set_fact:
    dummy_ec2_instance_id: "{{ ec2_dummy_result.instances[0].instance_id }}"
